// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vktkanivplhttwltcrjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrdGthbml2cGxodHR3bHRjcmpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MjY2NzgsImV4cCI6MjA3NjIwMjY3OH0.Gm0RZt_IJ00CDhhRgLVzLCG8iF4p3175Nds00PQm2OQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});